---
Commande: Serial.available()
---

= available()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Retourne le nombre d'octets (caractères) disponibles à la lecture à partir du port série. Il s'agit de données déjà arrivées et stockées dans le tampon de réception série (qui contient 64 octets).

`Serial.available()` est herité de la classe utilitaire :../../stream[Stream].
[%hardbreaks]


[float]
=== Syntaxe
`_Serial_.available()`


[float]
=== Paramètre
`_Serial_`: objet port série. Voir la liste des ports série disponibles pour chaque carte sur la link:../../serial[page d’accueil Série].


[float]
=== Retourne
Le nombre d'octets disponibles à la lecture.

--
// OVERVIEW SECTION ENDS

// HOW TO USE SECTION STARTS
[#howtouse]
--
[float]
=== Exemple
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
Le code suivant renvoie un caractère reçu via le port série.

[source,arduino]
----
int incomingByte = 0; // pour les données série entrantes

void setup() {
  Serial.begin(9600); // ouvre le port série, définit le débit de données à 9600 bps
}

void loop() {
  // répond uniquement lorsque des données sont reçues
  if (Serial.available() > 0) {

    // lecture de l'octet entrant
    incomingByte = Serial.read();

    // retourne ce qui est reçu
    Serial.print("octet reçu: ");
    Serial.println(incomingByte, DEC);
  }
}
----
[%hardbreaks]

*Exemple spécifique à l’Arduino Mega:*
Ce code renvoie les données reçues dans un port série de l'Arduino Mega vers un autre port série. Cela peut être utilisé, par exemple, pour connecter un périphérique série à l'ordinateur via la carte Arduino.

[source,arduino]
----
void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);
}

void loop() {
  // lecture depuis le port 0, renvoie vers le port 1:
  if (Serial.available()) {
    int inByte = Serial.read();
    Serial1.print(inByte, DEC);
  }
  // lecture depuis le port 1, renvoie vers le port 0:
  if (Serial1.available()) {
    int inByte = Serial1.read();
    Serial.print(inByte, DEC);
  }
}
----

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== See also

[role="language"]
* #LANGUAGE# link:../begin[begin()] +
* #LANGUAGE# link:../end[end()] +
* #LANGUAGE# link:../read[read()] +
* #LANGUAGE# link:../peek[peek()] +
* #LANGUAGE# link:../flush[flush()] +
* #LANGUAGE# link:../print[print()] +
* #LANGUAGE# link:../println[println()] +
* #LANGUAGE# link:../write[write()] +
* #LANGUAGE# link:../serialevent[SerialEvent()] +
* #LANGUAGE# link:../../stream/streamavailable[Stream.available()]

--
// SEE ALSO SECTION ENDS
