---
commande: Serial.begin()
---




= begin()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
Définit le débit de données en bits par seconde (BAUD) pour la transmission de données série. Pour communiquer avec Serial Monitor, assurez-vous d'utiliser l'un des taux de bauds répertoriés dans le menu dans le coin inférieur droit de son écran. Vous pouvez cependant spécifier d'autres taux - par exemple, pour communiquer sur les broches 0 et 1 avec un composant qui nécessite un taux de bauds particulier.

Un deuxième argument facultatif configure les données, la parité et les bits d'arrêt. La valeur par défaut est 8 bits de données, pas de parité, un bit d'arrêt.
[%hardbreaks]


[float]
=== Syntaxe
`_Serial_.begin(speed)` +
`_Serial_.begin(speed, config)`


[float]
=== Paramètres
`_Serial_`: objet de port série. Voir la liste des ports série disponibles pour chaque carte sur le lien :../../serial[Serial main page]. +
`speed`: en bits par seconde (baud). Types de données autorisées: `long`. +
`config`: Définit les données, la parité et les bits d'arrêt. Les valeurs valides sont: +
`SERIAL_5N1` +
`SERIAL_6N1` +
`SERIAL_7N1` +
`SERIAL_8N1` (par défaut) +
`SERIAL_5N2` +
`SERIAL_6N2` +
`SERIAL_7N2` +
`SERIAL_8N2` +
`SERIAL_5E1` +
`SERIAL_6E1` +
`SERIAL_7E1` +
`SERIAL_8E1` +
`SERIAL_5E2` +
`SERIAL_6E2` +
`SERIAL_7E2` +
`SERIAL_8E2` +
`SERIAL_5O1` +
`SERIAL_6O1` +
`SERIAL_7O1` +
`SERIAL_8O1` +
`SERIAL_5O2` +
`SERIAL_6O2` +
`SERIAL_7O2` +
`SERIAL_8O2`


[float]
=== Retourne
Rien

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== Examples
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
void setup() {
    Serial.begin(9600); // Ouvre le port série, défini le débit de données à 9600 bps
}

void loop() {}
----
[%hardbreaks]

*Exemple Arduino Mega:*
[source,arduino]
----
// Utilisation des 4 ports série de l’Arduino Mega
// (Serial, Serial1, Serial2, Serial3),
// chacun ayant un débit de données différent

void setup() {
  Serial.begin(9600);
  Serial1.begin(38400);
  Serial2.begin(19200);
  Serial3.begin(4800);

  Serial.println("Hello Computer");
  Serial1.println("Hello Serial 1");
  Serial2.println("Hello Serial 2");
  Serial3.println("Hello Serial 3");
}
void loop() {}
----
[%hardbreaks]
Merci à Jeff Gray pour cet exemple pour les cartes Mega


[float]
=== Notes et avertissements
For USB CDC serial ports (e.g. `Serial` on the Leonardo), `Serial.begin()` is irrelevant. You can use any baud rate and configuration for serial communication with these ports. See the list of available serial ports for each board on the link:../../serial[Serial main page].
Pour les ports série CDC en USB (ex. `Serial` sur carte Leonardo), `Serial.begin()` n'est pas pertinent. Vous pouvez utiliser n’importe quel configuration ou débit de données avec ces ports. Vous pouvez consulter la liste des ports série disponibles pour chaque carte ici :../../serial[Serial main page]
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
