---
Commande: Serial.find()
---




= Serial.find()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== Description
`Serial.find()` lit les données du tampon série jusqu'à ce que la cible soit trouvée. La fonction renvoie `true` si la cible est trouvée, `false` si elle expire.

`Serial.find()` est herité de la classe utilitaire link:../../stream[Stream].
[%hardbreaks]


[float]
=== Syntaxe
`_Serial_.find(target)` +
`_Serial_.find(target, length)`


[float]
=== Paramètres
`_Serial_`: objet port série. Voir la liste des ports série disponibles pour chaque carte sur la link:../../serial[page d’accueil Série]. +
`target`: la chaine de caractère à rechercher. Type de donnée autorisé: `char`. +
`length`: longueur de la cible. Type de donnée autorisé: `size_t`.


[float]
=== Retourne
Type: `bool`.

--
// OVERVIEW SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== A voir aussi

[role="language"]
* #LANGUAGE# link:../../stream[stream] +
* #LANGUAGE# link:../../stream/streamfind[stream.find()]

--
// SEE ALSO SECTION ENDS
